---
title: "nfl start"
author: "JMeerse"
date: "`r Sys.Date()`"
output: html_document
---
#libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nflfastR)
library(ggimage)

```
#R markdown
This will introduce using RStudio for analyzing NFL data./

Specifically, we'll look at the 2021 season (started in Sept 2021, ended in Feb 2022).

#data and 3rd down passing
```{r}
pbp22 <- load_pbp(2021)

#which team passed the most on 3rd down (outside of last 2 mins, game still in play)?
kc <- pbp22 %>%
  filter(wp > .20 & wp < .80 & down == 3 & half_seconds_remaining > 120) %>%
  group_by(posteam) %>%
  summarize(mean_pass = mean(pass), 
            plays = n()) %>%
  arrange(mean_pass)


#basic graph
ggplot(kc, aes(x = reorder(posteam,-mean_pass), 
               y = mean_pass)) + 
  geom_text(aes(label = posteam))

#does 3rd down passing depend on yards to go?
ytg <- pbp22 %>%
  filter(wp > .20 & wp < .80 & down == 3 & half_seconds_remaining > 120) %>%
  group_by(posteam) %>%
  summarize(mean_ytg = mean(ydstogo), 
            plays = n()) %>%
  arrange(mean_ytg)

#add ytg to kc
kc <- left_join(kc, ytg, by = "posteam")

#let's graph ytg vs pass%
p1 <- kc %>% ggplot(aes(x = mean_ytg, y = mean_pass)) +
  geom_text(aes(label = posteam))

#playing with themes, and adding labels
p1 + theme_bw()
p1 + theme_minimal()
p1 + theme_classic()
p1 + theme_void()

#ave ytg on 3rd down vs ave yards gained on passing on 3rd down
gained <- pbp22 %>%
  filter(wp > .20 & wp < .80 & down == 3 & half_seconds_remaining > 120 & pass == 1) %>%
  group_by(posteam) %>%
  summarize(mean_gain = mean(yards_gained, na.rm = TRUE), 
            plays = n()) %>%
  arrange(mean_gain)

#graph of mean_gain
ggplot(gained, aes(x = reorder(posteam,-mean_gain), 
               y = mean_gain)) + 
  geom_text(aes(label = posteam))

kc <- left_join(kc, gained, by = "posteam")

#scatterplot of yards to go and gain
p2 <- kc %>% ggplot(aes(x = mean_ytg, y = mean_gain)) +
  geom_text(aes(label = posteam))

p2

#add y = x
p2 + geom_abline(slope = 1, intercept = 0)

#let's get helmets!
kc  <- left_join(kc, teams_colors_logos, by = c("posteam" = "team_abbr"))

p3 <- kc %>% ggplot(aes(x = mean_ytg, y = mean_gain)) +
  geom_image(aes(image = team_logo_espn), 
             size = 0.05, by = "width",
             position = position_jitter(width = .075, height = .075)) +
  geom_abline(slope = 1, intercept = 0)

p3

#making nice labels
p4 <- p3 + labs(title = "3rd Down Passing, 2022, Yards to Go vs Yards Gained",
          subtitle = "Win Probability between 20% and 80%, excluding the last 2 mins of a half",
          caption = "@jmeerse  data: nflfastR",
          x = "Mean Yards to Go",
          y = "Mean Yards Gained by Passing")

#epa on 3rd down passing

epa3 <- pbp22 %>%
  filter(wp > .20 & wp < .80 & down == 3 & half_seconds_remaining > 120 & pass == 1) %>%
  group_by(posteam) %>%
  summarize(mean_epa = mean(epa, na.rm = TRUE), 
            plays = n()) %>%
  arrange(mean_epa)

#graph of mean_epa
ggplot(epa3, aes(x = reorder(posteam,-mean_epa), 
               y = mean_epa)) + 
  geom_text(aes(label = posteam))

#join to kc
kc <- left_join(kc, epa3, by = "posteam")

#scatterplot of mean gain vs mean epa

kc %>% ggplot(aes(x = mean_gain, y = mean_epa, color = mean_ytg)) +
  geom_text(aes(label = posteam))

```


```{r what is EPA?}
first_down_run <- pbp22 %>% 
  filter(down == 1, play_type == "run")

first_down_run %>% ggplot(aes(x = epa)) + geom_histogram()

summary(first_down_run$epa)

#lets just group by down - ave epa 
all_plays_epa <- pbp22 %>% filter(play_type == "run" | play_type == "pass") %>%   group_by(down, play_type) %>% summarise(mean_epa_all = mean(epa, na.rm = TRUE)) %>% ungroup()
#turnovers have a big effect - let's remove them and see the difference


pbp22 %>% filter(play_type == "run" | play_type == "pass") %>%
  ggplot(aes(x = epa, y = down, group = down)) + geom_boxplot() + facet_wrap(~ play_type)

pbp22 %>% filter(play_type == "run" | play_type == "pass", turnover == 0) %>%
  ggplot(aes(x = epa, y = down, group = down)) + geom_boxplot() + facet_wrap(~ play_type)

#make a variable indicating turnover on the play
pbp22 <- pbp22 %>% mutate(turnover = if_else(fumble_lost == 1 | interception == 1, 1, 0))

#look at mean epa without turnovers
epa_no_turnovers <- pbp22 %>% filter(play_type == "run" | play_type == "pass", turnover == 0) %>%   group_by(down, play_type) %>% summarise(mean_epa_no = mean(epa, na.rm = TRUE))

epa_down <- cbind(all_plays_epa, epa_no_turnovers) #this is bad, because it duplicates column names

# Find Duplicate Column Names
duplicated_names <- duplicated(colnames(epa_down))

# Remove Duplicate Column Names
epa_down <- epa_down[!duplicated_names]

#what does a turnover cost, on average?
epa_down$diff = epa_down$mean_epa_no - epa_down$mean_epa_all

#how to graph this?
epa_down %>% ggplot(aes(x = mean_epa_all, y = mean_epa_no)) + geom_point() 

# how does yards gained relate to epa?
pbp22 %>% filter(play_type == "run", fumble == 0) %>% 
  ggplot(aes(x = yards_gained, y = epa)) + 
  geom_point() + facet_wrap(~ down)

big_minus_epa <- pbp22 %>% filter(epa < -10) #plays that lost lots of epa - all were turnovers returned for TDs
```

```{r epa and winning}
reg22 <- pbp22 %>% filter(season_type == "REG")

epa_win <- reg22 %>% group_by(posteam, game_id) %>% 
  summarise(tot_epa = sum(epa, na.rm = TRUE),
            result = mean(result),
            home = last(home_team),
            away = last(away_team),
            week = last(week)) %>% 
  ungroup()
    
epa_win <- epa_win %>% 
  mutate(win_loss = case_when(
    (posteam == home) & result > 0 ~ "win",
    (posteam != home) & result < 0 ~ "win",
    TRUE ~ "loss"
    )
  )
 
                            
epa_win %>% ggplot(aes(x = week, 
                       y = tot_epa, 
                       group = posteam)) + 
  geom_line() + 
  geom_point(aes(color = win_loss)) +
  facet_wrap(~ posteam) 

```